#!/data/data/com.termux/files/usr/bin/bash

# ============================================================
# QSOL MERKLE V1 — TARGETED PROVENANCE SEARCH
# ============================================================
#
# PURPOSE
# -------
# Determine whether the exact QSOL Merkle V1 specification has
# an explicit provenance record showing promotion, ratification,
# approval, adoption, or effective FROZEN status.
#
# THIS SCRIPT DOES NOT INFER AUTHORITY.
#
# Successful tests, architectural-freeze messages, and the word
# "promoted" when used for odd Merkle nodes are not sufficient
# evidence of specification promotion.
#
# CANONICAL SPECIFICATION
# -----------------------
# Path:
#   specification/MERKLE-V1.md
#
# Expected SHA-256:
#   596ad7225200b15aece0b29950e98ff69f1faffa9652a20aaae8fe70c2b16abf
#
# OUTPUT EVIDENCE
# ---------------
# evidence/conformance/merkle-v1-provenance-search.txt
#
# ============================================================

set -euo pipefail

# ------------------------------------------------------------
# 1. Establish the canonical workspace.
# ------------------------------------------------------------

cd "$HOME/qsol-evidence-fabric"

# ------------------------------------------------------------
# 2. Define canonical paths and cryptographic identity.
# ------------------------------------------------------------

SPEC="specification/MERKLE-V1.md"

OUT="evidence/conformance/merkle-v1-provenance-search.txt"

EXPECTED_SHA256="596ad7225200b15aece0b29950e98ff69f1faffa9652a20aaae8fe70c2b16abf"

mkdir -p evidence/conformance

# ------------------------------------------------------------
# 3. Verify that the specification exists and has the expected
#    cryptographic identity BEFORE searching it.
# ------------------------------------------------------------

test -f "$SPEC"

ACTUAL_SHA256="$(sha256sum "$SPEC" | awk '{print $1}')"

if [ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]; then
    echo "ERROR: specification SHA-256 mismatch" >&2
    echo "expected=$EXPECTED_SHA256" >&2
    echo "actual=$ACTUAL_SHA256" >&2
    exit 1
fi

# ------------------------------------------------------------
# 4. Write the evidence-search record.
#
#    The search covers:
#      - exact specification hash
#      - specification names
#      - qsol-merkle-v1
#      - promotion terminology
#      - approval/ratification/adoption terminology
#      - explicit FROZEN status
#      - Git history
#      - Git tags
#      - Git branches
#      - release/manifest/status candidates
#
#    No authority conclusion is generated by the search itself.
# ------------------------------------------------------------

{
    echo "============================================================"
    echo "QSOL MERKLE V1 TARGETED PROVENANCE SEARCH"
    echo "============================================================"

    printf 'workspace=%s\n' "$PWD"
    printf 'specification=%s\n' "$SPEC"
    printf 'specification_sha256=%s\n' "$ACTUAL_SHA256"

    echo
    echo "============================================================"
    echo "1. SPECIFICATION IDENTITY"
    echo "============================================================"

    sha256sum "$SPEC"
    wc -c "$SPEC"
    realpath "$SPEC"

    echo
    echo "============================================================"
    echo "2. TARGETED WORKSPACE / EVIDENCE SEARCH"
    echo "============================================================"

    # These expressions target provenance/status language.
    # "promoted" is intentionally included because the resulting
    # matches must later be classified as either status evidence
    # or unrelated Merkle construction terminology.

    grep -RniE \
        --exclude-dir=.git \
        --exclude='*.pyc' \
        --exclude='merkle-v1-provenance-search.txt' \
        --exclude='merkle_v1_provenance_search.sh' \
        '596ad7225200b15aece0b29950e98ff69f1faffa9652a20aaae8fe70c2b16abf|MERKLE-V1|MERKLE V1|qsol-merkle-v1|MERKLE_V1_STATUS|STATUS[[:space:]]*=[[:space:]]*FROZEN|STATUS:[[:space:]]*FROZEN|promot|ratif|approv|adopt|effective' \
        evidence specification 2>/dev/null || true

    echo
    echo "============================================================"
    echo "3. GIT FILE HISTORY"
    echo "============================================================"

    # --follow is used because the specification may have been
    # renamed during its history.
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then

        git log \
            --follow \
            --date=iso-strict \
            --format='commit=%H%nauthor=%an%nauthor_date=%aI%nsubject=%s%n---' \
            -- "$SPEC" 2>&1 || true

    else
        echo "git_repository=NOT_DETECTED"
    fi

    echo
    echo "============================================================"
    echo "4. ALL GIT HISTORY MATCHING PROMOTION / STATUS TERMS"
    echo "============================================================"

    # This searches commit subjects across reachable history.
    # A matching commit is only a candidate; its contents must
    # still establish an explicit status transition.
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then

        git log \
            --all \
            --date=iso-strict \
            --format='commit=%H%nauthor=%an%nauthor_date=%aI%nsubject=%s%n---' \
            --grep='MERKLE-V1\|MERKLE V1\|qsol-merkle-v1\|FROZEN\|PROMOT\|RATIF\|APPROV\|ADOPT\|EFFECTIVE' \
            -i 2>&1 || true

    else
        echo "git_repository=NOT_DETECTED"
    fi

    echo
    echo "============================================================"
    echo "5. GIT TAGS"
    echo "============================================================"

    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then

        git tag --list --sort=creatordate 2>&1 || true

    else
        echo "git_repository=NOT_DETECTED"
    fi

    echo
    echo "============================================================"
    echo "6. GIT BRANCHES"
    echo "============================================================"

    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then

        git branch \
            --all \
            --no-color 2>&1 || true

    else
        echo "git_repository=NOT_DETECTED"
    fi

    echo
    echo "============================================================"
    echo "7. RELEASE / MANIFEST / STATUS CANDIDATES"
    echo "============================================================"

    # These filenames are collected as provenance candidates.
    # Their presence alone does NOT establish authority.

    find . \
        -path './.git' -prune -o \
        -type f \
        \( \
            -iname '*release*' \
            -o -iname '*manifest*' \
            -o -iname '*status*' \
            -o -iname '*promotion*' \
            -o -iname '*approval*' \
            -o -iname '*ratif*' \
        \) \
        -print 2>/dev/null | sort || true

    echo
    echo "============================================================"
    echo "8. EVIDENTIARY RULE"
    echo "============================================================"

    echo "A valid promotion finding requires:"
    echo
    echo "  exact specification identity"
    echo "        +"
    echo "  explicit provenance/status event"
    echo "        +"
    echo "  connection between the event and MERKLE-V1"
    echo
    echo "The following are NOT sufficient by themselves:"
    echo "  - generic architectural freeze"
    echo "  - successful implementation tests"
    echo "  - vector conformance"
    echo "  - odd-node 'promoted' construction language"
    echo "  - presence of the word FROZEN in Section 16"
    echo
    echo "authority_inference=DISABLED"
    echo "promotion_inference=DISABLED"

    echo
    echo "============================================================"
    echo "9. SEARCH COMPLETION"
    echo "============================================================"

    echo "search_completed=true"

} > "$OUT"

# ------------------------------------------------------------
# 5. Report the resulting evidence artifact identity.
# ------------------------------------------------------------

echo
echo "============================================================"
echo "FINAL SEARCH ARTIFACT"
echo "============================================================"

printf 'path=%s\n' "$OUT"

wc -c "$OUT"

sha256sum "$OUT"

echo
echo "============================================================"
echo "SPECIFICATION IDENTITY RECHECK"
echo "============================================================"

sha256sum "$SPEC"

echo
echo "PROVENANCE SEARCH COMPLETE"
